server:
  port: 9999
  context-path: /uaa

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service?verifyServerCertificate=false&useSSL=true
    username: root
    password: root
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_absent

logging:
  level:
    org.springframework.security: DEBUG


security:
  basic:
    enabled: false
